# Generated by Django 3.1.7 on 2021-10-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211017_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='tmpslug', unique=True),
            preserve_default=False,
        ),
    ]
